tasks:
  - init: |
      python -m pip install --upgrade pip
      python -m pip install --user poetry
      poetry export --dev --without-hashes -f requirements.txt -o requirements.txt
      python -m pip install --user --progress-bar off -r requirements.txt .
