copyright: Copyright &copy; 2020 Macklan Weinstein
extra:
  social:
    - icon: fontawesome/solid/home
      link: https://wolfgangwazzlestrauss.com
    - icon: fontawesome/brands/github
      link: https://github.com/wolfgangwazzlestrauss
    - icon: fontawesome/solid/envelope
      link: mailto://wolfgangwazzlestrauss@gmail.com
extra_javascript:
  - https://unpkg.com/mermaid@8.4.8/dist/mermaid.min.js
  - js/index.js
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - toc:
      permalink: true
nav:
  - Home:
      - Home: index.md
      - License: license.md
      - Changelog: changelog.md
  - Install:
      - Install: learn/install.md
  - Learn:
      - Guide: learn/guide.md
      - FAQ: learn/faq.md
  - API:
      - API: api/index.md
      - CLI: api/cli.md
  - Contribute:
      - Develop: contrib/index.md
      - Roadmap: contrib/roadmap.md
plugins:
  - minify:
      minify_html: true
  - mkdocstrings
  - search
repo_name: yamltable
repo_url: https://github.com/wolfgangwazzlestrauss/yamltable
site_author: Macklan Weinstein
site_description: |
  CLI for working with YAML files files organized similar to a
  relational database table.
site_name: YamlTable
site_url: https://wolfgangwazzlestrauss.github.io/yamltable/index
theme:
  features:
    - navigation.tabs
  name: material
  palette:
    accent: cyan
    primary: teal
