copyright: Copyright &copy; 2020 Macklan Weinstein
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://wolfgangwazzlestrauss.com
    - icon: fontawesome/brands/github-alt
      link: https://github.com/wolfgangwazzlestrauss
    - icon: fontawesome/brands/github-alt
      link: mailto://wolfgangwazzlestrauss@gmail.com
extra_javascript:
  - https://unpkg.com/mermaid@8.4.8/dist/mermaid.min.js
  - js/index.js
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - toc:
      permalink: true
nav:
  - Home: index.md
  - Install:
      - src/install.md
  - Learn:
      - src/learn/index.md
  - API:
      - API: src/api/index.md
      - CLI: src/api/cli.md
  - Contribute:
      - Welcome: src/contrib/index.md
      - Roadmap: src/contrib/roadmap.md
plugins:
  - minify:
      minify_html: true
  - mkdocstrings
  - search
repo_name: yamltable
repo_url: https://github.com/wolfgangwazzlestrauss/yamltable
site_author: Macklan Weinstein
site_description: |
  CLI for working with YAML files files organized similar to a
  relational database table.
site_name: YamlTable
site_url: https://wolfgangwazzlestrauss.github.io/yamltable/index
theme:
  features:
    - tabs
  name: material
  palette:
    accent: cyan
    primary: teal
