# GitHub Actions workflow file.
#
# For more information, visit
# https://docs.github.com/actions/learn-github-actions.

name: build

# Make workflow run only for commits pushed or pull requests made to the develop
# and master branches.
on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  # Run linter tests on project files.
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout code repository
        uses: actions/checkout@v2
      - name: Install Node interpreter
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Python interpreter
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Cache Node packages
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-14_ubuntu-latest_${{ hashFiles('package-lock.json') }}
      - name: Cache Python packages
        uses: actions/cache@v2
        with:
          path: .venv
          key: python-3.9_ubuntu-latest_poetry-${{ hashFiles('poetry.lock') }}
      - name: Install Node packages
        run: |
          npm install
      - name: Install Python packages
        run: |
          python -m pip install poetry
          poetry config virtualenvs.in-project true
          poetry install -v
      - name: Run format tests
        run: |
          npm run prettier:test
      - name: Run linter tests
        run: |
          poetry run bandit -ilr src/
          poetry run black --check .
          poetry run flake8 scripts/ src/ tests/
          poetry run mypy scripts/ src/ tests/
          poetry run python scripts/build_docs.py

  # Run Python tests on code.
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        python: [3.6, 3.7, 3.8, 3.9]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Git checkout code repository
        uses: actions/checkout@v2
      - name: Install Python interpreter
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Cache Python packages
        uses: actions/cache@v2
        with:
          path: .venv
          key: >
            python-${{ matrix.python }}_${{ matrix.os }}_poetry-${{
            hashFiles('poetry.lock') }}
      - name: Install Python packages
        run: |
          python -m pip install poetry
          poetry config virtualenvs.in-project true
          poetry install -v
      - name: Run Python tests
        run: |
          poetry run pytest --doctest-modules src
          poetry run pytest --cov

  # Generate test code coverage report.
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout code repository
        uses: actions/checkout@v2
      - name: Install Python interpreter
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Cache Python packages
        uses: actions/cache@v2
        with:
          path: .venv
          key: python-3.9_ubuntu-latest_poetry-${{ hashFiles('poetry.lock') }}
      - name: Install Python packages
        run: |
          python -m pip install poetry
          poetry install -v
      - name: Create code coverage report
        run: |
          poetry run pytest --cov --cov-fail-under=0 --cov-report=xml
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.xml
