# GitHub Actions workflow file.
#
# For more information, visit
# https://docs.github.com/actions/learn-github-actions.

name: package

# Make workflow run only for pushed SemVer tags.
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  # Build Python package and publish to PyPI.
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout code repository
        uses: actions/checkout@v2
      - name: Install Python interpreter
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip poetry setuptools wheel
          poetry install -v --no-dev
      - name: Build Python package
        run: |
          poetry build
      - name: Extract Git tag
        shell: bash
        run: |
          echo "##[set-output name=tag;]$(echo ${GITHUB_REF#refs/tags/})"
        id: extract_tag
      - name: Create GitHub elease
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false
      - name: Upload release asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          # prettier-ignore
          asset_path: ./dist/yamltable-${{ steps.extract_tag.outputs.tag }}-py3-none-any.whl
          # prettier-ignore
          asset_name: yamltable-py3-none-any.whl
          asset_content_type: application/x-binary
      # Use PyPI publish action over Poetry publish to prevent PyPI password
      # from being printed in CI logs.
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
